!/**
 * Highcharts JS v13.0.0 (2026-06-11)
 * @module highcharts/themes/sand-signika
 * @requires highcharts
 *
 * (c) 2009-2026 Highsoft AS
 * Author: Torstein Hønsi
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(t._Highcharts):"function"==typeof define&&define.amd?define("highcharts/themes/sand-signika",["highcharts/highcharts"],function(t){return e(t)}):"object"==typeof exports?exports["highcharts/themes/sand-signika"]=e(t._Highcharts):t.Highcharts=e(t.Highcharts)}("u"<typeof window?this:window,function(t){return function(){"use strict";var e,r,o={944:function(e){e.exports=t}},a={};function n(t){var e=a[t];if(void 0!==e)return e.exports;var r=a[t]={exports:{}};return o[t](r,r.exports,n),r.exports}n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,{a:e}),e},n.d=function(t,e){for(var r in e)n.o(e,r)&&!n.o(t,r)&&Object.defineProperty(t,r,{enumerable:!0,get:e[r]})},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)};var i={};n.d(i,{default:function(){return u}});var l=n(944),s=n.n(l),h=s().setOptions;(e=r||(r={})).options={palette:{light:{backgroundColor:"#f7f7f7",colors:["#f45b5b","#8085e9","#8d4654","#7798BF","#aaeeee","#ff0066","#eeaaee","#55BF3B","#DF5353","#7798BF","#aaeeee"]}},chart:{backgroundColor:"light-dark(transparent, #141414)",style:{fontFamily:"Signika, serif"}},title:{style:{color:"var(--highcharts-neutral-color-100)",fontSize:"16px",fontWeight:"bold"}},subtitle:{style:{color:"var(--highcharts-neutral-color-100)"}},tooltip:{borderWidth:0,backgroundColor:"var(--highcharts-neutral-color-80)",style:{color:"var(--highcharts-background-color)"}},legend:{backgroundColor:"var(--highcharts-neutral-color-10)",itemStyle:{fontWeight:"bold",fontSize:"13px"}},xAxis:{labels:{style:{color:"var(--highcharts-neutral-color-60)"}}},yAxis:{labels:{style:{color:"var(--highcharts-neutral-color-60)"}}},plotOptions:{series:{shadow:!0,dataLabels:{color:"light-dark(#000, #fff)",style:{textOutline:"none"}}},map:{shadow:!1}},global:{buttonTheme:{fill:"light-dark(#fff, #000)",stroke:"var(--highcharts-neutral-color-20)",states:{select:{fill:"var(--highcharts-neutral-color-10)"}}}},rangeSelector:{buttonTheme:{"stroke-width":1}}},e.apply=function(){(0,l.createElement)("link",{href:"https://fonts.googleapis.com/css?family=Signika:400,700",rel:"stylesheet",type:"text/css"},null,document.getElementsByTagName("head")[0]),(0,l.addEvent)(s().Chart,"afterGetContainer",function(){this.container.style.background="url(https://www.highcharts.com/samples/graphics/sand.png)"}),h(e.options)};var c=r;s().theme=c.options,c.apply();var u=s();return i.default}()});