
CREATE TABLE [dbo].[rhfp_atoseventos](
	[at_ev_id] [int] IDENTITY(1,1) NOT NULL,
	[ALA-DP-MATRICULA] [int] NULL,
	[ALA-DP-CPF-SERVIDOR] [varchar](11) NULL,
	[ALA-DP-NOME-SERVIDOR] [varchar](70) NULL,
	[ALA-AE-VALIDADE-ATO] [varchar](8) NULL,
	[ALA-AE-CODIGO-ATO] [int] NULL,
	[ae_atos_eventos] [varchar](100) NULL,
	[ALA-AE-NUMERO-DIARIO] [int] NULL,
	[ALA-AE-DATA-ATO] [varchar](8) NULL,
	[ALA-AE-DATA-FINAL] [varchar](8) NULL,
	[ALA-AE-PRAZO] [int] NULL,
	[ALA-AE-TIPO-ATO] [int] NULL,
	[taf_tipo_ato_funcional] [varchar](100) NULL,
	[QUADRO-ORIGINAL] [int] NULL,
	[CODIGO-ORIGINAL] [int] NULL,
	[SIMBOLO-ORIGINAL] [varchar](12) NULL,
	[CARGO-ORIGINAL] [varchar](79) NULL,
	[QUADRO-ACUMULADO] [int] NULL,
	[CODIGO-ACUMULADO] [int] NULL,
	[SIMBOLO-ACUMULADO] [varchar](12) NULL,
	[CARGO-ACUMULADO] [varchar](79) NULL,
	[VALIDADE-COMISSAO] [int] NULL,
	[CODIGO-COMISSAO] [int] NULL,
	[SIMBOLO-COMISSAO] [varchar](12) NULL,
	[CARGO-COMISSAO] [varchar](79) NULL,
	[VALIDADE-GRATIFICADA] [int] NULL,
	[CODIGO-GRATIFICADA] [int] NULL,
	[SIMBOLO-GRATIFICADA] [varchar](12) NULL,
	[CARGO-GRATIFICADA] [varchar](79) NULL,
	[ALA-AE-HISTORICO] [text] NULL,
	[INSTRUMENTO-LEGAL] [varchar](150) NULL,
	[ARTIGO-LEGAL] [varchar](30) NULL,
	[INCISO-LEGAL] [varchar](20) NULL,
	[ALINEA-LEGAL] [varchar](10) NULL,
	[PARAGRAFO-LEGAL] [varchar](20) NULL,
	[DATA-INICIO-AQUISITIVO] [varchar](8) NULL,
	[DATA-FINAL-AQUISITIVO] [varchar](8) NULL
 CONSTRAINT [PK_rhfp_atoseventos] PRIMARY KEY CLUSTERED 
(
	[at_ev_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
 



