USE [pms_rhfp_desenvolvimento]
 
INSERT INTO [dbo].[rhfp_dadosfuncionais]
           ([ALA-DP-MATRICULA]
           ,[ALA-DP-NOME-SERVIDOR]
           ,[ALA-DP-CPF-SERVIDOR]
           ,[ALA-FU-TIPO-CARGO]
           ,[ALA-FU-VALIDADE-INICIAL]
           ,[COD-SIMBOLO]
           ,[cs_simbolo]
           ,[cs_cargo]
           ,[PROVIMENTO]
           ,[pr_provimento]
           ,[ALA-FU-SITUACAO-FUNCIONAL]
           ,[sf_situacao_funcional]
           ,[ORGAO-SUPERIOR]
           ,[os_orgao]
           ,[UNIDADE-ORCAM]
           ,[os_unidade_ordamentaria]
           ,[MUNICIPIO]
           ,[mc_municipio]
           ,[REPARTICAO]
           ,[sf_reparticao])

SELECT [ALA-DP-MATRICULA]
      ,[ALA-DP-NOME-SERVIDOR]
      ,[ALA-DP-CPF-SERVIDOR]
      ,[ALA-FU-TIPO-CARGO]
      ,[ALA-FU-VALIDADE-INICIAL]
      ,[COD-SIMBOLO]
      ,[cs_simbolo]
      ,[cs_cargo]
      ,[PROVIMENTO]
      ,[pr_provimento]
      ,[ALA-FU-SITUACAO-FUNCIONAL]
      ,[sf_situacao_funcional]
      ,[ORGAO-SUPERIOR]
      ,[os_orgao]
      ,[UNIDADE-ORCAM]
      ,[os_unidade_ordamentaria]
      ,[MUNICIPIO]
      ,[mc_municipio]
      ,[REPARTICAO]
      ,[sf_reparticao]
  FROM [pms_rhfp_desenvolvimento].[dbo].[rhfp_dadosfuncionais_]
GO


