USE [pms_rhfp_desenvolvimento]
 


INSERT INTO [dbo].[rhfp_atoseventos]
           ([ALA-DP-MATRICULA]
           ,[ALA-DP-CPF-SERVIDOR]
           ,[ALA-DP-NOME-SERVIDOR]
           ,[ALA-AE-VALIDADE-ATO]
           ,[ALA-AE-CODIGO-ATO]
           ,[ae_atos_eventos]
           ,[ALA-AE-NUMERO-DIARIO]
           ,[ALA-AE-DATA-ATO]
           ,[ALA-AE-DATA-FINAL]
           ,[ALA-AE-PRAZO]
           ,[ALA-AE-TIPO-ATO]
           ,[taf_tipo_ato_funcional]
           ,[QUADRO-ORIGINAL]
           ,[CODIGO-ORIGINAL]
           ,[SIMBOLO-ORIGINAL]
           ,[CARGO-ORIGINAL]
           ,[QUADRO-ACUMULADO]
           ,[CODIGO-ACUMULADO]
           ,[SIMBOLO-ACUMULADO]
           ,[CARGO-ACUMULADO]
           ,[VALIDADE-COMISSAO]
           ,[CODIGO-COMISSAO]
           ,[SIMBOLO-COMISSAO]
           ,[CARGO-COMISSAO]
           ,[VALIDADE-GRATIFICADA]
           ,[CODIGO-GRATIFICADA]
           ,[SIMBOLO-GRATIFICADA]
           ,[CARGO-GRATIFICADA]
           ,[ALA-AE-HISTORICO]
           ,[INSTRUMENTO-LEGAL]
           ,[ARTIGO-LEGAL]
           ,[INCISO-LEGAL]
           ,[ALINEA-LEGAL]
           ,[PARAGRAFO-LEGAL]
           ,[DATA-INICIO-AQUISITIVO]
           ,[DATA-FINAL-AQUISITIVO])

SELECT  [ALA-DP-MATRICULA]
      ,[ALA-DP-CPF-SERVIDOR]
      ,[ALA-DP-NOME-SERVIDOR]
      ,[ALA-AE-VALIDADE-ATO]
      ,[ALA-AE-CODIGO-ATO]
      ,[ae_atos_eventos]
      ,[ALA-AE-NUMERO-DIARIO]
      ,[ALA-AE-DATA-ATO]
      ,[ALA-AE-DATA-FINAL]
      ,[ALA-AE-PRAZO]
      ,[ALA-AE-TIPO-ATO]
      ,[taf_tipo_ato_funcional]
      ,[QUADRO-ORIGINAL]
      ,[CODIGO-ORIGINAL]
      ,[SIMBOLO-ORIGINAL]
      ,[CARGO-ORIGINAL]
      ,[QUADRO-ACUMULADO]
      ,[CODIGO-ACUMULADO]
      ,[SIMBOLO-ACUMULADO]
      ,[CARGO-ACUMULADO]
      ,[VALIDADE-COMISSAO]
      ,[CODIGO-COMISSAO]
      ,[SIMBOLO-COMISSAO]
      ,[CARGO-COMISSAO]
      ,[VALIDADE-GRATIFICADA]
      ,[CODIGO-GRATIFICADA]
      ,[SIMBOLO-GRATIFICADA]
      ,[CARGO-GRATIFICADA]
      ,[ALA-AE-HISTORICO]
      ,[INSTRUMENTO-LEGAL]
      ,[ARTIGO-LEGAL]
      ,[INCISO-LEGAL]
      ,[ALINEA-LEGAL]
      ,[PARAGRAFO-LEGAL]
      ,[DATA-INICIO-AQUISITIVO]
      ,[DATA-FINAL-AQUISITIVO]
  FROM [pms_rhfp_desenvolvimento].[dbo].[rhfp_atoseventos_]
GO
 