!/**
 * Highstock JS v13.0.0 (2026-06-11)
 * @module highcharts/indicators/ao
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Wojciech Chmiel
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(t,r){"object"==typeof exports&&"object"==typeof module?module.exports=r(t._Highcharts,t._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/ao",["highcharts/highcharts"],function(t){return r(t,t.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/ao"]=r(t._Highcharts,t._Highcharts.SeriesRegistry):t.Highcharts=r(t.Highcharts,t.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(t,r){return function(){"use strict";var o,e={512:function(t){t.exports=r},944:function(r){r.exports=t}},n={};function i(t){var r=n[t];if(void 0!==r)return r.exports;var o=n[t]={exports:{}};return e[t](o,o.exports,i),o.exports}i.n=function(t){var r=t&&t.__esModule?function(){return t.default}:function(){return t};return i.d(r,{a:r}),r},i.d=function(t,r){for(var o in r)i.o(r,o)&&!i.o(t,o)&&Object.defineProperty(t,o,{enumerable:!0,get:r[o]})},i.o=function(t,r){return Object.prototype.hasOwnProperty.call(t,r)};var a={};i.d(a,{default:function(){return v}});var s=i(944),c=i.n(s),u=i(512),p=i.n(u),h=(o=function(t,r){return(o=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(t,r){t.__proto__=r}||function(t,r){for(var o in r)r.hasOwnProperty(o)&&(t[o]=r[o])})(t,r)},function(t,r){function e(){this.constructor=t}o(t,r),t.prototype=null===r?Object.create(r):(e.prototype=r.prototype,new e)}),l=c().noop,f=p().seriesTypes,d=f.column.prototype,g=f.sma,y=function(t){function r(){return null!==t&&t.apply(this,arguments)||this}return h(r,t),r.prototype.drawGraph=function(){var t,r=this.options,o=this.points,e=this.userOptions.color,n=r.greaterBarColor,i=r.lowerBarColor,a=o[0];if(!e&&a)for(t=1,a.color=n;t<o.length;t++)o[t].y>o[t-1].y?o[t].color=n:o[t].y<o[t-1].y?o[t].color=i:o[t].color=o[t-1].color},r.prototype.getValues=function(t){var r,o,e,n,i,a,c,u,p=t.xData||[],h=t.yData||[],l=h.length,f=[],d=[],g=[],y=0,v=0;if(!(p.length<=34)&&(0,s.isArray)(h[0])&&4===h[0].length){for(c=0;c<33;c++)a=(h[c][1]+h[c][2])/2,c>=29&&(v=(0,s.correctFloat)(v+a)),y=(0,s.correctFloat)(y+a);for(u=33;u<l;u++)a=(h[u][1]+h[u][2])/2,v=(0,s.correctFloat)(v+a),y=(0,s.correctFloat)(y+a),r=v/5,o=y/34,e=(0,s.correctFloat)(r-o),f.push([p[u],e]),d.push(p[u]),g.push(e),n=u+1-5,i=u+1-34,v=(0,s.correctFloat)(v-(h[n][1]+h[n][2])/2),y=(0,s.correctFloat)(y-(h[i][1]+h[i][2])/2);return{values:f,xData:d,yData:g}}},r.defaultOptions=(0,s.merge)(g.defaultOptions,{params:{index:void 0,period:void 0},greaterBarColor:"var(--highcharts-positive-color)",lowerBarColor:"var(--highcharts-negative-color)",threshold:0,groupPadding:.2,pointPadding:.2,crisp:!1,states:{hover:{halo:{size:0}}}}),r}(g);(0,s.extend)(y.prototype,{nameBase:"AO",nameComponents:void 0,markerAttribs:l,getColumnMetrics:d.getColumnMetrics,crispCol:d.crispCol,translate:d.translate,drawPoints:d.drawPoints}),p().registerSeriesType("ao",y);var v=c();return a.default}()});