!/**
 * Highstock JS v13.0.0 (2026-06-11)
 * @module highcharts/indicators/psar
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Parabolic SAR Indicator for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Grzegorz Blachliński
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(t._Highcharts,t._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/psar",["highcharts/highcharts"],function(t){return e(t,t.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/psar"]=e(t._Highcharts,t._Highcharts.SeriesRegistry):t.Highcharts=e(t.Highcharts,t.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(t,e){return function(){"use strict";var r,n={512:function(t){t.exports=e},944:function(e){e.exports=t}},i={};function o(t){var e=i[t];if(void 0!==e)return e.exports;var r=i[t]={exports:{}};return n[t](r,r.exports,o),r.exports}o.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return o.d(e,{a:e}),e},o.d=function(t,e){for(var r in e)o.o(e,r)&&!o.o(t,r)&&Object.defineProperty(t,r,{enumerable:!0,get:e[r]})},o.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)};var a={};o.d(a,{default:function(){return y}});var c=o(944),s=o.n(c),u=o(512),p=o.n(u),h=(r=function(t,e){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var r in e)e.hasOwnProperty(r)&&(t[r]=e[r])})(t,e)},function(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}),l=p().seriesTypes.sma;function f(t,e){return parseFloat(t.toFixed(e))}var d=function(t){function e(){var e=null!==t&&t.apply(this,arguments)||this;return e.nameComponents=void 0,e}return h(e,t),e.prototype.getValues=function(t,e){var r,n,i,o,a,c,s,u,p,h,l,d,y,m,g,x,v,_,b,O,F,j,w,A,H,M,P,S,D,R,T,W,k,C=t.xData,V=t.yData,q=e.maxAccelerationFactor,z=e.increment,B=e.initialAccelerationFactor,E=e.decimals,G=e.index,I=[],J=[],K=[],L=e.initialAccelerationFactor,N=V[0][1],Q=1,U=V[0][2];if(!(G>=V.length)){for(k=0;k<G;k++)N=Math.max(V[k][1],N),U=Math.min(V[k][2],f(U,E));for(j=V[k][1]>U?1:-1,w=N-U,A=(L=e.initialAccelerationFactor)*w,I.push([C[G],U]),J.push(C[G]),K.push(f(U,E)),k=G+1;k<V.length;k++)if(M=V[k-1][2],P=V[k-2][2],S=V[k-1][1],D=V[k-2][1],T=V[k][1],W=V[k][2],null!==P&&null!==D&&null!==M&&null!==S&&null!==T&&null!==W){r=j,n=Q,i=U,o=A,a=P,c=M,s=S,u=D,p=N,U=r===n?1===r?i+o<Math.min(a,c)?i+o:Math.min(a,c):i+o>Math.max(u,s)?i+o:Math.max(u,s):p,_=j,b=N,R=1===_?T>b?T:b:W<b?W:b,O=Q,F=U,h=H=1===O&&W>F||-1===O&&T>F?1:-1,l=j,d=R,y=N,m=L,g=z,x=q,v=B,A=(L=h===l?1===h&&d>y||-1===h&&d<y?m===x?x:f(m+g,2):m:v)*(w=R-U),I.push([C[k],f(U,E)]),J.push(C[k]),K.push(f(U,E)),Q=j,j=H,N=R}return{values:I,xData:J,yData:K}}},e.defaultOptions=(0,c.merge)(l.defaultOptions,{lineWidth:0,marker:{enabled:!0},states:{hover:{lineWidthPlus:0}},params:{period:void 0,initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,index:2,decimals:4}}),e}(l);p().registerSeriesType("psar",d);var y=s();return a.default}()});