!/**
 * Highstock JS v13.0.0 (2026-06-11)
 * @module highcharts/indicators/tema
 * @requires highcharts
 * @requires highcharts/modules/stock
 *
 * Indicator series type for Highcharts Stock
 *
 * (c) 2010-2026 Highsoft AS
 * Author: Rafał Sebestjański
 *
 * A commercial license may be required depending on use,
 * see www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(e._Highcharts,e._Highcharts.SeriesRegistry):"function"==typeof define&&define.amd?define("highcharts/indicators/tema",["highcharts/highcharts"],function(e){return t(e,e.SeriesRegistry)}):"object"==typeof exports?exports["highcharts/indicators/tema"]=t(e._Highcharts,e._Highcharts.SeriesRegistry):e.Highcharts=t(e.Highcharts,e.Highcharts.SeriesRegistry)}("u"<typeof window?this:window,function(e,t){return function(){"use strict";var r,o={512:function(e){e.exports=t},944:function(t){t.exports=e}},n={};function i(e){var t=n[e];if(void 0!==t)return t.exports;var r=n[e]={exports:{}};return o[e](r,r.exports,i),r.exports}i.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(t,{a:t}),t},i.d=function(e,t){for(var r in t)i.o(t,r)&&!i.o(e,r)&&Object.defineProperty(e,r,{enumerable:!0,get:t[r]})},i.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)};var l={};i.d(l,{default:function(){return v}});var s=i(944),u=i.n(s),a=i(512),c=i.n(a),p=(r=function(e,t){return(r=Object.setPrototypeOf||({__proto__:[]})instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(e,t)},function(e,t){function o(){this.constructor=e}r(e,t),e.prototype=null===t?Object.create(t):(o.prototype=t.prototype,new o)}),h=c().seriesTypes.ema,f=function(e){function t(){return null!==e&&e.apply(this,arguments)||this}return p(t,e),t.prototype.getEMA=function(t,r,o,n,i,l){return e.prototype.calculateEma.call(this,l||[],t,void 0===i?1:i,this.EMApercent,r,void 0===n?-1:n,o)},t.prototype.getTemaPoint=function(e,t,r,o){return[e[o-3],(0,s.correctFloat)(3*r.level1-3*r.level2+r.level3)]},t.prototype.getValues=function(t,r){var o,n,i,l,u=r.period,a=2*u,c=3*u,p=t.xData,h=t.yData,f=h?h.length:0,v=[],y=[],d=[],g=[],x=[],_={},m=-1,A=0,O=0;if(this.EMApercent=2/(u+1),!(f<3*u-2)){for((0,s.isArray)(h[0])&&(m=r.index?r.index:0),O=(A=e.prototype.accumulatePeriodPoints.call(this,u,m,h))/u,A=0,i=u;i<f+3;i++)i<f+1&&(_.level1=this.getEMA(h,o,O,m,i)[1],g.push(_.level1)),o=_.level1,i<a?A+=_.level1:(i===a&&(O=A/u,A=0),_.level1=g[i-u-1],_.level2=this.getEMA([_.level1],n,O)[1],x.push(_.level2),n=_.level2,i<c?A+=_.level2:(i===c&&(O=A/u),i===f+1&&(_.level1=g[i-u-1],_.level2=this.getEMA([_.level1],n,O)[1],x.push(_.level2)),_.level1=g[i-u-2],_.level2=x[i-2*u-1],_.level3=this.getEMA([_.level2],_.prevLevel3,O)[1],(l=this.getTemaPoint(p,c,_,i))&&(v.push(l),y.push(l[0]),d.push(l[1])),_.prevLevel3=_.level3));return{values:v,xData:y,yData:d}}},t.defaultOptions=(0,s.merge)(h.defaultOptions),t}(h);c().registerSeriesType("tema",f);var v=u();return l.default}()});