//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHFP.ModelData.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rhfp_codigo_atos_eventos
    {
        public int ae_cod { get; set; }
        public string ae_atos_eventos { get; set; }
        public string ae_status { get; set; }
        public string ae_ato_texto { get; set; }
        public string ae_conta_vida_funcional { get; set; }
    }
}
