//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHFP.ModelData.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rhfp_cargo_simbolo
    {
        public int cs_cod { get; set; }
        public string cs_cargo { get; set; }
        public string cs_simbolo { get; set; }
        public Nullable<decimal> cs_valor_referencia { get; set; }
        public Nullable<int> cs_carga_horaria { get; set; }
        public Nullable<int> cs_ind_cargo { get; set; }
        public Nullable<decimal> cs_valor_auxiliar { get; set; }
        public string cs_cod_orcamentario { get; set; }
        public string cs_incidencias { get; set; }
    }
}
