//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHFP.ModelData.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rhfp_financeiro
    {
        public int fin_id { get; set; }
        public int ala_fi_MATRICULA { get; set; }
        public int tipo_cargo_fi { get; set; }
        public string ALA_DP_NOME_SERVIDOR { get; set; }
        public string ALA_DP_CPF_SERVIDOR { get; set; }
        public string COMPETENCIA_FI { get; set; }
        public int cod_rubrica_fi { get; set; }
        public string pr_Rubrica { get; set; }
        public string data_inicio_fi { get; set; }
        public Nullable<decimal> ala_fi_valor { get; set; }
        public Nullable<decimal> ala_fi_perc_pont_dia_hora { get; set; }
        public Nullable<decimal> ala_fi_QTDE_URV { get; set; }
    }
}
