//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHFP.ModelData.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rhfp_municipio
    {
        public int mc_cod { get; set; }
        public string mc_municipio { get; set; }
        public string mc_cod_uf { get; set; }
    }
}
