//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHFP.ModelData.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rhfp_banco_agencia
    {
        public int os_cod_banco { get; set; }
        public int os_cod_agencia { get; set; }
        public string os_agencia { get; set; }
    }
}
