//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHFP.ModelData.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rhfp_tipo_atos_eventos
    {
        public short tae_codigo { get; set; }
        public string tae_atos_eventos { get; set; }
        public string tae_situacao { get; set; }
    }
}
