//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHFP.ModelData.Database.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RHFPContext : DbContext
    {
        public RHFPContext()
            : base("name=RHFPContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rhfp_cargo_simbolo> rhfp_cargo_simbolo { get; set; }
        public virtual DbSet<rhfp_cbo> rhfp_cbo { get; set; }
        public virtual DbSet<rhfp_codigo_atos_eventos> rhfp_codigo_atos_eventos { get; set; }
        public virtual DbSet<rhfp_estado_civil> rhfp_estado_civil { get; set; }
        public virtual DbSet<rhfp_grau_instrucao> rhfp_grau_instrucao { get; set; }
        public virtual DbSet<rhfp_municipio> rhfp_municipio { get; set; }
        public virtual DbSet<rhfp_orgao_superior> rhfp_orgao_superior { get; set; }
        public virtual DbSet<rhfp_provimento> rhfp_provimento { get; set; }
        public virtual DbSet<rhfp_sexo> rhfp_sexo { get; set; }
        public virtual DbSet<rhfp_situacao_funcional> rhfp_situacao_funcional { get; set; }
        public virtual DbSet<rhfp_status> rhfp_status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<rhfp_banco> rhfp_banco { get; set; }
        public virtual DbSet<rhfp_banco_agencia> rhfp_banco_agencia { get; set; }
        public virtual DbSet<rhfp_faixas_imposto_renda> rhfp_faixas_imposto_renda { get; set; }
        public virtual DbSet<rhfp_financeiro> rhfp_financeiro { get; set; }
        public virtual DbSet<rhfp_grau_parentesco> rhfp_grau_parentesco { get; set; }
        public virtual DbSet<rhfp_orgao_externo> rhfp_orgao_externo { get; set; }
        public virtual DbSet<rhfp_orgao_unidade_orcamentaria> rhfp_orgao_unidade_orcamentaria { get; set; }
        public virtual DbSet<rhfp_paises> rhfp_paises { get; set; }
        public virtual DbSet<rhfp_quadro_cargo_original> rhfp_quadro_cargo_original { get; set; }
        public virtual DbSet<rhfp_reparticao> rhfp_reparticao { get; set; }
        public virtual DbSet<rhfp_rubricas> rhfp_rubricas { get; set; }
        public virtual DbSet<rhfp_seguradoras> rhfp_seguradoras { get; set; }
        public virtual DbSet<rhfp_tipo_ato_funcional> rhfp_tipo_ato_funcional { get; set; }
        public virtual DbSet<rhfp_tipo_dependencia> rhfp_tipo_dependencia { get; set; }
        public virtual DbSet<rhfp_valores_mensais> rhfp_valores_mensais { get; set; }
    }
}
